# Site settings
author: Mika Spivak
title: CodeWorld
header-img: img/home-bg.png
email: mikaspivak@gmail.com
copyright_name: Mika Spivak
description: > # this means to ignore newlines until "baseurl:"
  Sharing my exciting coding journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Mika88

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
